## This should be places in the plugin directory
## for more help configuring see the wiki
## https://github.com/alkarinv/BattleArena/wiki
## Change this file to customize your event

Futbol:
    enabled: true
    database: Futbol # or delete if you dont want wins/losses/top, needs BattleTracker
    rated: false # if database is enabled
    prefix: "&f[Futbol]&e"
    cmd: fb
    ### You can delete any stages/transitions that have no options
    ### for a list of options see wiki
    preReqs: ## Prerequisites for joining
        options: [clearInventory]
    onJoin:  ## when they join the match
        options: []
    onPreStart: ## x seconds before onStart
        options: []
    onStart: ## Starting
        options: [teleportIn, pvpOff, woolteams]
    onSpawn: ## what happens when a player spawns
        options: [hunger=20, health=20]
    onDeath: ## what happens when a player dies
        options: []
    onComplete: ## what happens when things end
        options: [teleportOut, pvpOn, clearInventory]
    winner: ## what to give the winner
        options: [health=20, hunger=20]
    losers: ## what to give the losers
        options: []
    victoryCondition: highestKills        
