## This should be placed in the plugin directory
## for more help configuring see the wiki
## https://github.com/alkarinv/BattleArena/wiki
## Change this file to customize your event

Futbol:
    enabled: true
    database: Futbol # or delete if you dont want wins/losses/top, needs BattleTracker
    rated: false # if database is enabled
    prefix: "&f[Futbol]&e"
    cmd: fb
    ### You can delete any stages/transitions that have no options
    ### for a list of options see wiki
    preReqs: ## Prerequisites for joining
        options: [clearInventory]
    onJoin:  ## when they join the match
        options: []
    onPreStart: ## x seconds before onStart
        options: []
    onStart: ## Starting
        options: [teleportIn, pvpOff, blockBreakOff, woolTeams]
    onSpawn: ## what happens when a player spawns
        options: [hunger=20, health=20]
    onDeath: ## what happens when a player dies
        options: []
    onComplete: ## what happens when things end
        options: [teleportOut, pvpOn, clearInventory, blockBreakOn]
    winner: ## what to give the winner
        options: [health=20, hunger=20, giveItems]
        items:
          - diamond: 1
          - emerald: 1
    losers: ## what to give the losers
        options: [health=20, hunger=20, giveItems]
        items:
          - emerald: 1
    nTeams: 2
    matchTime: 120 ## How long do timed matches last, (in seconds)
    matchUpdateInterval: 30 ## For timed matched, how long between sending players match updates
    victoryCondition: highestKills        
