name: ArenaFutbol
main: me.morrango.arenafutbol.ArenaFutbol
version: 0.3.5
website: http://
author: Morrango
depend: [BattleArena]

description: >
             version 2 of futbol
commands:
  futbol:
    description: arena futbol
    aliases: [fb]
    usage: |
           /fb
  maxfutbol:
    description: arena futbol
    aliases: [mfb]
    usage: |
           /mfb            
  arenafutbol:
    description: arena futbol
    aliases: [af]
    usage: |
           /af ball <int>, /af pitch <int>, /af maxpitch <int>, /af power <double>