name: ${project.name}
main: me.morrango.arenafutbol.FutbolPlugin
version: ${project.version}
website: ${project.url}
author: Morrango
authors: [Europia79, Redned]
depend: [BattleArena]
softdepend: [ProtocolLib]
description: ${project.description}
commands:
  futbol:
    description: arena futbol
    aliases: [fb]
    usage: /fb <ball|balltimer|pitch|maxpitch|power>
  worldcup:
    description: arena futbol
    aliases: [wc]
    usage:  /wc
